baseURL: "/"
title: "suwa3 blog"
paginate: 5
theme: "hugo-PaperMod"

params:
    homeInfoParams:
        Title: Hi there wave
        Content: Can be Info, links, about...

    socialIcons: # optional
#        - name: "<platform>"
#            url: "<link>"
#        - name: "<platform 2>"
#            url: "<link2>"
