baseURL: "/"
title: "suwa3 blog"
paginate: 5
theme: "github-style"

params:
    github: "Ishizuka427"
    twitter: "_Tsuka3"
    url: "https://suwa3.github.io"
    favicon: "https://avatars.githubusercontent.com/u/56011102?v=4" 
    homeInfoParams:
        Title: Hi there wave
        Content: Can be Info, links, about...

    socialIcons: # optional
#        - name: "<platform>"
#            url: "<link>"
#        - name: "<platform 2>"
#            url: "<link2>"
    links:
         - icon: "https://avatars.githubusercontent.com/u/56011102?v=4"
