baseURL: "https://hugo.suwa3.me/"
languageCode: "ja-JP"
title: "suwa3 blog"
paginate: 5
theme: "papercss-hugo-theme"
pygmentsCodeFences: "true"
pygmentsUseClasses: "true"
tag: "tags"
category: "categories"
toc: "true"
archive: "archives"

params:
    author: "suwa3"
    description: "In solitude, where we are least alone."
    github: "Ishizuka427"
    twitter: "_Tsuka3"
    url: "https://suwa3.github.io"
    favicon: "https://github.com/Ishizuka427/dot-Alien_Baltan/blob/master/images/Alien_Baltan.png"
    avatar: "https://avatars.githubusercontent.com/u/56011102?v=4"
#    rss: "true"
#    lastmod: "true"
    homeInfoParams:
        Title: Hi there wave
        Content: Can be Info, links, about...

    socialIcons: # optional
#        - name: "<platform>"
#            url: "<link>"
#        - name: "<platform 2>"
#            url: "<link2>"
    links:
         - icon: "https://avatars.githubusercontent.com/u/56011102?v=4"
frontmatter:
    lastmod:
         - :lastmod
         - :fileModTime
         - :default
